### ISSUE TITLE
Invisibility, name glow and size issue on login

### ISSUE THREAD

**Issue by NimacJanez** [solero/nostalgia#3]
After uploading the plugin to the server, everyone who log on is invisible, shrinks to lowest possible size and gets a black glow.

**Comment by ghost** [comment]
Did you follow the instructions? Also is this AS2 or AS3?

**Comment by NimacJanez** [comment]
I did it twice. There are others with this problem as well. I'm on AS3

**Comment by ghost** [comment]
I recommend to join the [Discord](https://discord.com/invite/87d42kd) to explain your issue in detail in the club-penguin channel.

**Comment by Bale001** [comment]
Are you sure this isn't a server sided issue?

**Comment by Bale001** [comment]
OK I figured it out. The issue is because of a change made in the recent version of houdini, because of the new way houdini handles empty values in player strings. To fix this issue, open the "houdini" folder, and then open __init__.py in an ide. Then go to line 120 and change this from:
`return p.get_custom_attribute(attribute_name, '')`
To:
`return p.get_custom_attribute(attribute_name, 0)`
This should fix your issue

**Comment by ghost** [comment]
You should fix this in the repo too

**Comment by NimacJanez** [comment]
That did the trick, thank you. Black glow is still present (for everyone by default), however it's not a big deal.
